### ISSUE TITLE
Comments for memeqstr and memeqzero are swapped.

### ISSUE THREAD

**Issue by allanbank** [rustyrussell/ccan#32]
See https://github.com/rustyrussell/ccan/blob/master/ccan/mem/mem.h#L133 and https://github.com/rustyrussell/ccan/blob/master/ccan/mem/mem.h#L150.

**Comment by rustyrussell** [comment]
allanbank <notifications@github.com> writes:
> See https://github.com/rustyrussell/ccan/blob/master/ccan/mem/mem.h#L133 and https://github.com/rustyrussell/ccan/blob/master/ccan/mem/mem.h#L150.

Thanks!  Not quite sure how I messed that up.

Cheers,
Rusty.
