### ISSUE TITLE
tal/path/path_join reads outside buffer with empty base string

### ISSUE THREAD

**Issue by russdill** [rustyrussell/ccan#61]
When path_join is called with path_join(NULL, "", "foo"), the code reads 1 byte before the allocated return buffer:

  51         len = strlen(base);
  52         ret = tal_dup_arr(ctx, char, base, len, 1 + strlen(a) + 1);
  53         if (!ret)
  54                 goto out;
  55         if (ret[len-1] != PATH_SEP)
  56                 ret[len++] = PATH_SEP;

When len is 0, ret[len-1] reads 1 byte before the allocated return buffer.

**Comment by rustyrussell** [comment]
Russ Dill <notifications@github.com> writes:
> When path_join is called with path_join(NULL, "", "foo"), the code reads 1 byte before the allocated return buffer:
>
>   51         len = strlen(base);
>   52         ret = tal_dup_arr(ctx, char, base, len, 1 + strlen(a) + 1);
>   53         if (!ret)
>   54                 goto out;
>   55         if (ret[len-1] != PATH_SEP)
>   56                 ret[len++] = PATH_SEP;
>
> When len is 0, ret[len-1] reads 1 byte before the allocated return buffer.

Hmm, I was assuming base was actually a path, not "".

Because you *don't* want "/foo" in this case, you presumably want "foo"?

Cheers,
Rusty.

**Comment by russdill** [comment]
Probably just "foo", anything is probably fine though so long as it's documented as not being supported but still avoids the outside of buffer access if it gets one.

**Comment by gitgofred** [comment]
ln 53 chg not req

**Comment by gitgofred** [comment]
perhaps a sort of unlikely_path to eye any off by one before ret = tal_dup_arr(...)?

**Comment by gitgofred** [comment]
53 comment logic and if (0 -- len) not useful on second parse.

**Comment by gitgofred** [comment]
nice stitch.
