### ISSUE TITLE
HAVE_UCONTEXT check on musl libc

### ISSUE THREAD

**Issue by jsarenik** [rustyrussell/ccan#66]
The `HAVE_UCONTEXT` check returns false on musl-based system (Alpine Linux for example), but is not true because there is the `/usr/include/ucontext.h` file and after manually changing `config.h` file the compilation works pretty well until another error - reported separately and I will link it here.

**Comment by jsarenik** [comment]
I can provide SSH access to such a system if needed.

**Comment by rustyrussell** [comment]
Ján Sáreník <notifications@github.com> writes:
> I can provide SSH access to such a system if needed.

Hmm, I wonder what went wrong?  Here's what configurator tries to run:

#include <ucontext.h>
static int x = 0;
static char stack[2048];
static ucontext_t a, b;
static void fn(void) {
	x |= 2;
	setcontext(&b);
	x |= 4;
}
int main(void) {
	x |= 1;
	getcontext(&a);
	a.uc_stack.ss_sp = stack;
	a.uc_stack.ss_size = sizeof(stack);
	makecontext(&a, fn, 0);
	swapcontext(&b, &a);
	return (x == 3) ? 0 : 1;
}

Does that compile and run?

Thanks!
Rusty.

**Comment by jsarenik** [comment]
Hi Rusty!

Very good point. It does not compile.

According to discussion at http://www.openwall.com/lists/musl/2016/02/04/5 and linked POSIX source there, the interface is obsolete and these alternative libc (uClibc, musl, ...) are already not implementing it. Though I wonder why they keep the header file...

Thanks!
Jasan

**Comment by dgibson** [comment]
Yeah, it's kind of annoying.  Apparently ucontext is deprecated, but I'm not at all sure what you're supposed to use instead.

**Comment by jsarenik** [comment]
Just for note: https://stackoverflow.com/questions/4298986/is-there-something-to-replace-the-ucontext-h-functions

They say there:

> Edit (based on OP's request): To implement "cooperative threading" with pthreads, you need condition variables. Here's a decent pthreads tutorial with information on using them:
> 
> https://computing.llnl.gov/tutorials/pthreads/#ConditionVariables
> 
> Your cooperative multitasking primitive of "hand off execution to thread X" would go something like:
> 
> ```
> self->flag = 0;
> other_thread->flag = 1;
> pthread_mutex_lock(other_thread->mutex);
> pthread_cond_signal(other_thread->cond);
> pthread_mutex_unlock(other_thread->mutex);
> pthread_mutex_lock(self->mutex);
> while (!self->flag)
>     pthread_cond_wait(self->cond, self->mutex);
> pthread_mutex_unlock(self->mutex);
> ```
> Hope I got that all right; at least the general idea is correct. If anyone sees mistakes please comment so I can fix it. Half of the locking (other_thread's mutex) is probably entirely unnecessary with this sort of usage, so you could perhaps make the mutex a local variable in the task_switch function. All you'd really be doing is using pthread_cond_wait and pthread_cond_signal as "go to sleep" and "wake up other thread" primitives.

@dgibson What do you think? Would it be possible to reimplement it using pthreads?

**Comment by dgibson** [comment]
Possible, yeah, I guess. Sensible, no.  Implementing threads in terms of coroutines is something you do if you need, implemeting coroutines in terms of threads is just bizarrely backwards.

**Comment by jsarenik** [comment]
@dgibson OK, so what about https://github.com/0intro/libtask ?

**Comment by dgibson** [comment]
Well, sure, there's that and plenty of other coroutine libraries out there.  The trouble is once it's not something you can count on being in the system libraries using it becomes much more of a pain.  Maybe needing the extra library depending on what your system library has gets even uglier.

Plus you have to think, if you're relying on yet another library, would anyone actually want to use the ccan module rather than the other library directly.

**Comment by jsarenik** [comment]
I see. Actually my original point is over because I can compile and run all
the tests for C-Lightning (which uses ccan) on a must based system.

So as for me, the issue can be closed.

**Comment by jsarenik** [comment]
Feel free to reopen whenever it's interesting for the developers. I'm closing for myself.
